In [1]:
import pandas as pd
import numpy as np 
data = pd.read_csv('titanic/train.csv') # Comma Separated Values - Valores Separados Por Vírgula
data.columns = ['IdPassageiro', 'Sobreviveu', 'Classe', 'Nome', 'Sexo', 'Idade', 
                'IrmaoConjuge', 'PaisFilhos', 'Bilhete', 'Tarifa', 'Cabine', 'Embarque']
data['Sexo'].replace({'male': 'homem', 'female': 'mulher'}, inplace=True)
data.head()

,IdPassageiro,Sobreviveu,Classe,Nome,Sexo,Idade,IrmaoConjuge,PaisFilhos,Bilhete,Tarifa,Cabine,Embarque
0,1,0,3,"Braund, Mr. Owen Harris",homem,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",mulher,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",mulher,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",mulher,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",homem,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
data.apply(lambda x: (x+10)  if x.name == 'Classe' else x)

In [ ]:
df = pd.DataFrame({'X': [1, 2, 3,],
                   'Y': [4, 1, 8]})
print("Original DataFrame")
print(df)
modified_df=df.apply(lambda x: (x*2)  if x.name == 'X' else x)
print("Modified DataFrame")
print(modified_df)

In [ ]:
data['Bilhete'].sort_values()

In [ ]:
x = '110413'

In [ ]:
x[:-1]

In [ ]:
data['Bilhete'] = data['Bilhete'].apply(lambda x: x + 'A').sort_values()

In [ ]:
def soma(*args):
    return sum(args)

data['Tarifa'].apply(soma, args=(2,5))

In [ ]:
data.apply(lambda x: 'Tarifa' if x.Tarifa > x.Idade else 'Idade', axis=1)

In [ ]:
data['Classe'] = data['Classe'].apply(lambda x: 5 if x== 2 else x)
data['Classe'].unique()

In [ ]:
data['Classe'].value_counts()

In [ ]:
def calculate_area(row):
    return row.sum()

data = {
  "x": [50, 40, 30],
  "y": [300, 1112, 42]
}

df = pd.DataFrame(data)

x = df.apply(lambda x: x.sum() if x.name == 'Classe' else x)

print(x)

In [ ]:
data['Somatória'] = data['Tarifa']
data = data.apply(lambda x: x.sum() if x.name == 'Somatória' else x)
data

In [ ]:
def calculate_area(row):
    if row['x']:
        return row['x'] * row['y']

data = {
  "x": [50, 40, 30],
  "y": [300, 1112, 42]
}

df = pd.DataFrame(data)

x = df.apply(lambda x , axis=1)

print(x)

In [ ]:
data.apply(lambda x: 'Tarifa' if x.Tarifa > x.Idade else 'Idade', axis=1)

In [ ]:
data['Tarifa'].apply(np.square, raw=False)

In [ ]:
data.apply(lambda x: 'Tarifa' if x.Tarifa > x.Idade else 'Idade', axis=1)

In [ ]:
data['Classe'].unique()

In [ ]:
data.apply(lambda x: 'Tarifa' if x.Tarifa > x.Idade else 'Idade', axis=1, result_type='broadcast')

In [ ]:
data.apply(lambda x: x.Tarifa, axis=1, result_type='expand')

In [ ]:
pd.get_dummies(data, columns=['Sexo'], prefix="Column")

In [ ]:
from category_encoders.one_hot import OneHotEncoder

# criação do df com os dados categoricos
df_cats = data.select_dtypes(include='object') 
one_hot = OneHotEncoder(cols=['Sexo'])
one_hot.fit_transform(df_cats)

In [ ]:
data['Nome'].str.extract('\w')

In [43]:
for indice, linha in data.iterrows():
    print(f'Indice: {indice}')
    print(f'linha: \n{linha}')
    break

Indice: 0
linha:
IdPassageiro                          1
Sobreviveu                            0
Classe                                3
Nome            Braund, Mr. Owen Harris
Sexo                              homem
Idade                              22.0
IrmaoConjuge                          1
PaisFilhos                            0
Bilhete                       A/5 21171
Tarifa                             7.25
Cabine                              NaN
Embarque                              S
Classe Nova                 Classe alta
Name: 0, dtype: object

In [3]:
for i in data.iterrows():
    print(f'Linha: {i[0]}')
    print(f'Colunas: \n{i[1]}')
    break

Linha: 0
Colunas:
IdPassageiro                          1
Sobreviveu                            0
Classe                                3
Nome            Braund, Mr. Owen Harris
Sexo                              homem
Idade                              22.0
IrmaoConjuge                          1
PaisFilhos                            0
Bilhete                       A/5 21171
Tarifa                             7.25
Cabine                              NaN
Embarque                              S
Name: 0, dtype: object

In [4]:
print(f'Linha: {i[0]}')
valores = []print(f'Colunas: \n{i[1]}')

Linha: 0
Colunas:
IdPassageiro                          1
Sobreviveu                            0
Classe                                3
Nome            Braund, Mr. Owen Harris
Sexo                              homem
Idade                              22.0
IrmaoConjuge                          1
PaisFilhos                            0
Bilhete                       A/5 21171
Tarifa                             7.25
Cabine                              NaN
Embarque                              S
Name: 0, dtype: object

In [13]:
%%timeit -r1
classe = []
for indice, linha in data.iterrows():
    classe.append('Classe alta' if linha['Classe'] ==3 else 'Classe')
data['Classe Nova'] = classe
data

49.4 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)

In [14]:
%%timeit -r1
classe = []
for linha in data.itertuples():
    classe.append('Classe alta' if linha.Classe ==3 else 'Classe')
data['Classe Nova'] = classe
data

3.22 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)

In [23]:
classe = []
for indice, linha in data.iteritems():
    print(indice)
    print(linha)
    break

IdPassageiro
0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: IdPassageiro, Length: 891, dtype: int64

In [26]:
for i in data.iterrows():
    print(f'Linha: {i[0]}')
    print(f'Colunas: \n{i[1]}')

Linha: 0
Colunas:
IdPassageiro                          1
Sobreviveu                            0
Classe                                3
Nome            Braund, Mr. Owen Harris
Sexo                              homem
Idade                              22.0
IrmaoConjuge                          1
PaisFilhos                            0
Bilhete                       A/5 21171
Tarifa                             7.25
Cabine                              NaN
Embarque                              S
Classe Nova                 Classe alta
Name: 0, dtype: object
Linha: 1
Colunas:
IdPassageiro                                                    2
Sobreviveu                                                      1
Classe                                                          1
Nome            Cumings, Mrs. John Bradley (Florence Briggs Th...
Sexo                                                       mulher
Idade                                                        38.0
IrmaoConjuge                                                    1
PaisFilhos                                                      0
Bilhete                                                  PC 17599
Tarifa                                                    71.2833
Cabine                                                        C85
Embarque                                                        C
Classe Nova                                                Classe
Name: 1, dtype: object
Linha: 2
Colunas:
IdPassageiro                         3
Sobreviveu                           1
Classe                               3
Nome            Heikkinen, Miss. Laina
Sexo                            mulher
Idade                             26.0
IrmaoConjuge                         0
PaisFilhos                           0
Bilhete               STON/O2. 3101282
Tarifa                           7.925
Cabine                             NaN
Embarque                             S
Classe Nova                Classe alta
Name: 2, dtype: object
Linha: 3
Colunas:
IdPassageiro                                               4
Sobreviveu                                                 1
Classe                                                     1
Nome            Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sexo                                                  mulher
Idade                                                   35.0
IrmaoConjuge                                               1
PaisFilhos                                                 0
Bilhete                                               113803
Tarifa                                                  53.1
Cabine                                                  C123
Embarque                                                   S
Classe Nova                                           Classe
Name: 3, dtype: object
Linha: 4
Colunas:
IdPassageiro                           5
Sobreviveu                             0
Classe                                 3
Nome            Allen, Mr. William Henry
Sexo                               homem
Idade                               35.0
IrmaoConjuge                           0
PaisFilhos                             0
Bilhete                           373450
Tarifa                              8.05
Cabine                               NaN
Embarque                               S
Classe Nova                  Classe alta
Name: 4, dtype: object
Linha: 5
Colunas:
IdPassageiro                   6
Sobreviveu                     0
Classe                         3
Nome            Moran, Mr. James
Sexo                       homem
Idade                        NaN
IrmaoConjuge                   0
PaisFilhos                     0
Bilhete                   330877
Tarifa                    8.4583
Cabine                       NaN
Embarque                       Q
Classe Nova          Classe alta
Name: 5, dtype: object
Linha: 6
Colunas:
IdPassageiro                          7
Sobreviveu                            0
Classe                                1
Nome            McCarthy, Mr. Timothy J
Sexo                              homem
Idade                              54.0
IrmaoConjuge                          0
PaisFilhos                            0
Bilhete                           17463
Tarifa                          51.8625
Cabine                              E46
Embarque                              S
Classe Nova                      Classe
Name: 6, dtype: object
Linha: 7
Colunas:
IdPassageiro                                 8
Sobreviveu                                   0
Classe                                       3
Nome            Palsson, Master. Gosta Leonard
Sexo                                     homem
Idade                                      2.0
IrmaoConjuge                                 3
PaisFilhos                                   1
Bilhete                                 349909
Tarifa                                  21.075
Cabine                                     NaN
Embarque                                     S
Classe Nova                        Classe alta
Name: 7, dtype: object
Linha: 8
Colunas:
IdPassageiro                                                    9
Sobreviveu                                                      1
Classe                                                          3
Nome            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
Sexo                                                       mulher
Idade                                                        27.0
IrmaoConjuge                                                    0
PaisFilhos                                                      2
Bilhete                                                    347742
Tarifa                                                    11.1333
Cabine                                                        NaN
Embarque                                                        S
Classe Nova                                           Classe alta
Name: 8, dtype: object
Linha: 9
Colunas:
IdPassageiro                                     10
Sobreviveu                                        1
Classe                                            2
Nome            Nasser, Mrs. Nicholas (Adele Achem)
Sexo                                         mulher
Idade                                          14.0
IrmaoConjuge                                      1
PaisFilhos                                        0
Bilhete                                      237736
Tarifa                                      30.0708
Cabine                                          NaN
Embarque                                          C
Classe Nova                                  Classe
Name: 9, dtype: object
Linha: 10
Colunas:
IdPassageiro                                 11
Sobreviveu                                    1
Classe                                        3
Nome            Sandstrom, Miss. Marguerite Rut
Sexo                                     mulher
Idade                                       4.0
IrmaoConjuge                                  1
PaisFilhos                                    1
Bilhete                                 PP 9549
Tarifa                                     16.7
Cabine                                       G6
Embarque                                      S
Classe Nova                         Classe alta
Name: 10, dtype: object
Linha: 11
Colunas:
IdPassageiro                          12
Sobreviveu                             1
Classe                                 1
Nome            Bonnell, Miss. Elizabeth
Sexo                              mulher
Idade                               58.0
IrmaoConjuge                           0
PaisFilhos                             0
Bilhete                           113783
Tarifa                             26.55
Cabine                              C103
Embarque                               S
Classe Nova                       Classe
Name: 11, dtype: object
Linha: 12
Colunas:
IdPassageiro                                13
Sobreviveu                                   0
Classe                                       3
Nome            Saundercock, Mr. William Henry
Sexo                                     homem
Idade                                     20.0
IrmaoConjuge                                 0
PaisFilhos                                   0
Bilhete                              A/5. 2151
Tarifa                                    8.05
Cabine                                     NaN
Embarque                                     S
Classe Nova                        Classe alta
Name: 12, dtype: object
Linha: 13
Colunas:
IdPassageiro                             14
Sobreviveu                                0
Classe                                    3
Nome            Andersson, Mr. Anders Johan
Sexo                                  homem
Idade                                  39.0
IrmaoConjuge                              1
PaisFilhos                                5
Bilhete                              347082
Tarifa                               31.275
Cabine                                  NaN
Embarque                                  S
Classe Nova                     Classe alta
Name: 13, dtype: object
Linha: 14
Colunas:
IdPassageiro                                      15
Sobreviveu                                         0
Classe                                             3
Nome            Vestrom, Miss. Hulda Amanda Adolfina
Sexo                                          mulher
Idade                                           14.0
IrmaoConjuge                                       0
PaisFilhos                                         0
Bilhete                                       350406
Tarifa                                        7.8542
Cabine                                           NaN
Embarque                                           S
Classe Nova                              Classe alta
Name: 14, dtype: object
Linha: 15
Colunas:
IdPassageiro                                  16
Sobreviveu                                     1
Classe                                         2
Nome            Hewlett, Mrs. (Mary D Kingcome)
Sexo                                      mulher
Idade                                       55.0
IrmaoConjuge                                   0
PaisFilhos                                     0
Bilhete                                   248706
Tarifa                                      16.0
Cabine                                       NaN
Embarque                                       S
Classe Nova                               Classe
Name: 15, dtype: object
Linha: 16
Colunas:
IdPassageiro                      17
Sobreviveu                         0
Classe                             3
Nome            Rice, Master. Eugene
Sexo                           homem
Idade                            2.0
IrmaoConjuge                       4
PaisFilhos                         1
Bilhete                       382652
Tarifa                        29.125
Cabine                           NaN
Embarque                           Q
Classe Nova              Classe alta
Name: 16, dtype: object
Linha: 17
Colunas:
IdPassageiro                              18
Sobreviveu                                 1
Classe                                     2
Nome            Williams, Mr. Charles Eugene
Sexo                                   homem
Idade                                    NaN
IrmaoConjuge                               0
PaisFilhos                                 0
Bilhete                               244373
Tarifa                                  13.0
Cabine                                   NaN
Embarque                                   S
Classe Nova                           Classe
Name: 17, dtype: object
Linha: 18
Colunas:
IdPassageiro                                                   19
Sobreviveu                                                      0
Classe                                                          3
Nome            Vander Planke, Mrs. Julius (Emelia Maria Vande...
Sexo                                                       mulher
Idade                                                        31.0
IrmaoConjuge                                                    1
PaisFilhos                                                      0
Bilhete                                                    345763
Tarifa                                                       18.0
Cabine                                                        NaN
Embarque                                                        S
Classe Nova                                           Classe alta
Name: 18, dtype: object
Linha: 19
Colunas:
IdPassageiro                         20
Sobreviveu                            1
Classe                                3
Nome            Masselmani, Mrs. Fatima
Sexo                             mulher
Idade                               NaN
IrmaoConjuge                          0
PaisFilhos                            0
Bilhete                            2649
Tarifa                            7.225
Cabine                              NaN
Embarque                              C
Classe Nova                 Classe alta
Name: 19, dtype: object
Linha: 20
Colunas:
IdPassageiro                      21
Sobreviveu                         0
Classe                             2
Nome            Fynney, Mr. Joseph J
Sexo                           homem
Idade                           35.0
IrmaoConjuge                       0
PaisFilhos                         0
Bilhete                       239865
Tarifa                          26.0
Cabine                           NaN
Embarque                           S
Classe Nova                   Classe
Name: 20, dtype: object
Linha: 21
Colunas:
IdPassageiro                       22
Sobreviveu                          1
Classe                              2
Nome            Beesley, Mr. Lawrence
Sexo                            homem
Idade                            34.0
IrmaoConjuge                        0
PaisFilhos                          0
Bilhete                        248698
Tarifa                           13.0
Cabine                            D56
Embarque                            S
Classe Nova                    Classe
Name: 21, dtype: object
Linha: 22
Colunas:
IdPassageiro                             23
Sobreviveu                                1
Classe                                    3
Nome            McGowan, Miss. Anna "Annie"
Sexo                                 mulher
Idade                                  15.0
IrmaoConjuge                              0
PaisFilhos                                0
Bilhete                              330923
Tarifa                               8.0292
Cabine                                  NaN
Embarque                                  Q
Classe Nova                     Classe alta
Name: 22, dtype: object
Linha: 23
Colunas:
IdPassageiro                              24
Sobreviveu                                 1
Classe                                     1
Nome            Sloper, Mr. William Thompson
Sexo                                   homem
Idade                                   28.0
IrmaoConjuge                               0
PaisFilhos                                 0
Bilhete                               113788
Tarifa                                  35.5
Cabine                                    A6
Embarque                                   S
Classe Nova                           Classe
Name: 23, dtype: object
Linha: 24
Colunas:
IdPassageiro                               25
Sobreviveu                                  0
Classe                                      3
Nome            Palsson, Miss. Torborg Danira
Sexo                                   mulher
Idade                                     8.0
IrmaoConjuge                                3
PaisFilhos                                  1
Bilhete                                349909
Tarifa                                 21.075
Cabine                                    NaN
Embarque                                    S
Classe Nova                       Classe alta
Name: 24, dtype: object
Linha: 25
Colunas:
IdPassageiro                                                   26
Sobreviveu                                                      1
Classe                                                          3
Nome            Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
Sexo                                                       mulher
Idade                                                        38.0
IrmaoConjuge                                                    1
PaisFilhos                                                      5
Bilhete                                                    347077
Tarifa                                                    31.3875
Cabine                                                        NaN
Embarque                                                        S
Classe Nova                                           Classe alta
Name: 25, dtype: object
Linha: 26
Colunas:
IdPassageiro                         27
Sobreviveu                            0
Classe                                3
Nome            Emir, Mr. Farred Chehab
Sexo                              homem
Idade                               NaN
IrmaoConjuge                          0
PaisFilhos                            0
Bilhete                            2631
Tarifa                            7.225
Cabine                              NaN
Embarque                              C
Classe Nova                 Classe alta
Name: 26, dtype: object
Linha: 27
Colunas:
IdPassageiro                                28
Sobreviveu                                   0
Classe                                       1
Nome            Fortune, Mr. Charles Alexander
Sexo                                     homem
Idade                                     19.0
IrmaoConjuge                                 3
PaisFilhos                                   2
Bilhete                                  19950
Tarifa                                   263.0
Cabine                             C23 C25 C27
Embarque                                     S
Classe Nova                             Classe
Name: 27, dtype: object
Linha: 28
Colunas:
IdPassageiro                               29
Sobreviveu                                  1
Classe                                      3
Nome            O'Dwyer, Miss. Ellen "Nellie"
Sexo                                   mulher
Idade                                     NaN
IrmaoConjuge                                0
PaisFilhos                                  0
Bilhete                                330959
Tarifa                                 7.8792
Cabine                                    NaN
Embarque                                    Q
Classe Nova                       Classe alta
Name: 28, dtype: object
Linha: 29
Colunas:
IdPassageiro                     30
Sobreviveu                        0
Classe                            3
Nome            Todoroff, Mr. Lalio
Sexo                          homem
Idade                           NaN
IrmaoConjuge                      0
PaisFilhos                        0
Bilhete                      349216
Tarifa                       7.8958
Cabine                          NaN
Embarque                          S
Classe Nova             Classe alta
Name: 29, dtype: object
Linha: 30
Colunas:
IdPassageiro                          31
Sobreviveu                             0
Classe                                 1
Nome            Uruchurtu, Don. Manuel E
Sexo                               homem
Idade                               40.0
IrmaoConjuge                           0
PaisFilhos                             0
Bilhete                         PC 17601
Tarifa                           27.7208
Cabine                               NaN
Embarque                               C

Name: 233, dtype: object
Linha: 234
Colunas:
IdPassageiro                                  235
Sobreviveu                                      0
Classe                                          2
Nome            Leyson, Mr. Robert William Norman
Sexo                                        homem
Idade                                        24.0
IrmaoConjuge                                    0
PaisFilhos                                      0
Bilhete                                C.A. 29566
Tarifa                                       10.5
Cabine                                        NaN
Embarque                                        S
Classe Nova                                Classe
Name: 234, dtype: object
Linha: 235
Colunas:
IdPassageiro                             236
Sobreviveu                                 0
Classe                                     3
Nome            Harknett, Miss. Alice Phoebe
Sexo                                  mulher
Idade                                    NaN
IrmaoConjuge                               0
PaisFilhos                                 0
Bilhete                           W./C. 6609
Tarifa                                  7.55
Cabine                                   NaN
Embarque                                   S
Classe Nova                      Classe alta
Name: 235, dtype: object
Linha: 236
Colunas:
IdPassageiro                  237
Sobreviveu                      0
Classe                          2
Nome            Hold, Mr. Stephen
Sexo                        homem
Idade                        44.0
IrmaoConjuge                    1
PaisFilhos                      0
Bilhete                     26707
Tarifa                       26.0
Cabine                        NaN
Embarque                        S
Classe Nova                Classe
Name: 236, dtype: object
Linha: 237
Colunas:
IdPassageiro                                 238
Sobreviveu                                     1
Classe                                         2
Nome            Collyer, Miss. Marjorie "Lottie"
Sexo                                      mulher
Idade                                        8.0
IrmaoConjuge                                   0
PaisFilhos                                     2
Bilhete                               C.A. 31921
Tarifa                                     26.25
Cabine                                       NaN
Embarque                                       S
Classe Nova                               Classe
Name: 237, dtype: object
Linha: 238
Colunas:
IdPassageiro                                239
Sobreviveu                                    0
Classe                                        2
Nome            Pengelly, Mr. Frederick William
Sexo                                      homem
Idade                                      19.0
IrmaoConjuge                                  0
PaisFilhos                                    0
Bilhete                                   28665
Tarifa                                     10.5
Cabine                                      NaN
Embarque                                      S
Classe Nova                              Classe
Name: 238, dtype: object
Linha: 239
Colunas:
IdPassageiro                       240
Sobreviveu                           0
Classe                               2
Nome            Hunt, Mr. George Henry
Sexo                             homem
Idade                             33.0
IrmaoConjuge                         0
PaisFilhos                           0
Bilhete                     SCO/W 1585
Tarifa                          12.275
Cabine                             NaN
Embarque                             S
Classe Nova                     Classe
Name: 239, dtype: object
Linha: 240
Colunas:
IdPassageiro                      241
Sobreviveu                          0
Classe                              3
Nome            Zabour, Miss. Thamine
Sexo                           mulher
Idade                             NaN
IrmaoConjuge                        1
PaisFilhos                          0
Bilhete                          2665
Tarifa                        14.4542
Cabine                            NaN
Embarque                            C
Classe Nova               Classe alta
Name: 240, dtype: object
Linha: 241
Colunas:
IdPassageiro                               242
Sobreviveu                                   1
Classe                                       3
Nome            Murphy, Miss. Katherine "Kate"
Sexo                                    mulher
Idade                                      NaN
IrmaoConjuge                                 1
PaisFilhos                                   0
Bilhete                                 367230
Tarifa                                    15.5
Cabine                                     NaN
Embarque                                     Q
Classe Nova                        Classe alta
Name: 241, dtype: object
Linha: 242
Colunas:
IdPassageiro                                243
Sobreviveu                                    0
Classe                                        2
Nome            Coleridge, Mr. Reginald Charles
Sexo                                      homem
Idade                                      29.0
IrmaoConjuge                                  0
PaisFilhos                                    0
Bilhete                             W./C. 14263
Tarifa                                     10.5
Cabine                                      NaN
Embarque                                      S
Classe Nova                              Classe
Name: 242, dtype: object
Linha: 243
Colunas:
IdPassageiro                              244
Sobreviveu                                  0
Classe                                      3
Nome            Maenpaa, Mr. Matti Alexanteri
Sexo                                    homem
Idade                                    22.0
IrmaoConjuge                                0
PaisFilhos                                  0
Bilhete                     STON/O 2. 3101275
Tarifa                                  7.125
Cabine                                    NaN
Embarque                                    S
Classe Nova                       Classe alta
Name: 243, dtype: object
Linha: 244
Colunas:
IdPassageiro                     245
Sobreviveu                         0
Classe                             3
Nome            Attalah, Mr. Sleiman
Sexo                           homem
Idade                           30.0
IrmaoConjuge                       0
PaisFilhos                         0
Bilhete                         2694
Tarifa                         7.225
Cabine                           NaN
Embarque                           C
Classe Nova              Classe alta
Name: 244, dtype: object
Linha: 245
Colunas:
IdPassageiro                            246
Sobreviveu                                0
Classe                                    1
Nome            Minahan, Dr. William Edward
Sexo                                  homem
Idade                                  44.0
IrmaoConjuge                              2
PaisFilhos                                0
Bilhete                               19928
Tarifa                                 90.0
Cabine                                  C78
Embarque                                  Q
Classe Nova                          Classe
Name: 245, dtype: object
Linha: 246
Colunas:
IdPassageiro                                      247
Sobreviveu                                          0
Classe                                              3
Nome            Lindahl, Miss. Agda Thorilda Viktoria
Sexo                                           mulher
Idade                                            25.0
IrmaoConjuge                                        0
PaisFilhos                                          0
Bilhete                                        347071
Tarifa                                          7.775
Cabine                                            NaN
Embarque                                            S
Classe Nova                               Classe alta
Name: 246, dtype: object
Linha: 247
Colunas:
IdPassageiro                                248
Sobreviveu                                    1
Classe                                        2
Nome            Hamalainen, Mrs. William (Anna)
Sexo                                     mulher
Idade                                      24.0
IrmaoConjuge                                  0
PaisFilhos                                    2
Bilhete                                  250649
Tarifa                                     14.5
Cabine                                      NaN
Embarque                                      S
Classe Nova                              Classe
Name: 247, dtype: object
Linha: 248
Colunas:
IdPassageiro                              249
Sobreviveu                                  1
Classe                                      1
Nome            Beckwith, Mr. Richard Leonard
Sexo                                    homem
Idade                                    37.0
IrmaoConjuge                                1
PaisFilhos                                  1
Bilhete                                 11751
Tarifa                                52.5542
Cabine                                    D35
Embarque                                    S
Classe Nova                            Classe
Name: 248, dtype: object
Linha: 249
Colunas:
IdPassageiro                              250
Sobreviveu                                  0
Classe                                      2
Nome            Carter, Rev. Ernest Courtenay
Sexo                                    homem
Idade                                    54.0
IrmaoConjuge                                1
PaisFilhos                                  0
Bilhete                                244252
Tarifa                                   26.0
Cabine                                    NaN
Embarque                                    S
Classe Nova                            Classe
Name: 249, dtype: object
Linha: 250
Colunas:
IdPassageiro                       251
Sobreviveu                           0
Classe                               3
Nome            Reed, Mr. James George
Sexo                             homem
Idade                              NaN
IrmaoConjuge                         0
PaisFilhos                           0
Bilhete                         362316
Tarifa                            7.25
Cabine                             NaN
Embarque                             S
Classe Nova                Classe alta
Name: 250, dtype: object
Linha: 251
Colunas:
IdPassageiro                                           252
Sobreviveu                                               0
Classe                                                   3
Nome            Strom, Mrs. Wilhelm (Elna Matilda Persson)
Sexo                                                mulher
Idade                                                 29.0
IrmaoConjuge                                             1
PaisFilhos                                               1
Bilhete                                             347054
Tarifa                                             10.4625
Cabine                                                  G6
Embarque                                                 S
Classe Nova                                    Classe alta
Name: 251, dtype: object
Linha: 252
Colunas:
IdPassageiro                          253
Sobreviveu                              0
Classe                                  1
Nome            Stead, Mr. William Thomas
Sexo                                homem
Idade                                62.0
IrmaoConjuge                            0
PaisFilhos                              0
Bilhete                            113514
Tarifa                              26.55
Cabine                                C87
Embarque                                S
Classe Nova                        Classe
Name: 252, dtype: object
Linha: 253
Colunas:
IdPassageiro                         254
Sobreviveu                             0
Classe                                 3
Nome            Lobb, Mr. William Arthur
Sexo                               homem
Idade                               30.0
IrmaoConjuge                           1
PaisFilhos                             0
Bilhete                        A/5. 3336
Tarifa                              16.1
Cabine                               NaN
Embarque                               S
Classe Nova                  Classe alta
Name: 253, dtype: object
Linha: 254
Colunas:
IdPassageiro                                         255
Sobreviveu                                             0
Classe                                                 3
Nome            Rosblom, Mrs. Viktor (Helena Wilhelmina)
Sexo                                              mulher
Idade                                               41.0
IrmaoConjuge                                           0
PaisFilhos                                             2
Bilhete                                           370129
Tarifa                                           20.2125
Cabine                                               NaN
Embarque                                               S
Classe Nova                                  Classe alta
Name: 254, dtype: object
Linha: 255
Colunas:
IdPassageiro                                        256
Sobreviveu                                            1
Classe                                                3
Nome            Touma, Mrs. Darwis (Hanne Youssef Razi)
Sexo                                             mulher
Idade                                              29.0
IrmaoConjuge                                          0
PaisFilhos                                            2
Bilhete                                            2650
Tarifa                                          15.2458
Cabine                                              NaN
Embarque                                              C
Classe Nova                                 Classe alta
Name: 255, dtype: object
Linha: 256
Colunas:
IdPassageiro                               257
Sobreviveu                                   1
Classe                                       1
Nome            Thorne, Mrs. Gertrude Maybelle
Sexo                                    mulher
Idade                                      NaN
IrmaoConjuge                                 0
PaisFilhos                                   0
Bilhete                               PC 17585
Tarifa                                    79.2
Cabine                                     NaN
Embarque                                     C
Classe Nova                             Classe
Name: 256, dtype: object
Linha: 257
Colunas:
IdPassageiro                     258
Sobreviveu                         1
Classe                             1
Nome            Cherry, Miss. Gladys
Sexo                          mulher
Idade                           30.0
IrmaoConjuge                       0
PaisFilhos                         0
Bilhete                       110152
Tarifa                          86.5
Cabine                           B77
Embarque                           S
Classe Nova                   Classe
Name: 257, dtype: object
Linha: 258
Colunas:
IdPassageiro                 259
Sobreviveu                     1
Classe                         1
Nome            Ward, Miss. Anna
Sexo                      mulher
Idade                       35.0
IrmaoConjuge                   0
PaisFilhos                     0
Bilhete                 PC 17755
Tarifa                  512.3292
Cabine                       NaN
Embarque                       C
Classe Nova               Classe
Name: 258, dtype: object
Linha: 259
Colunas:
IdPassageiro                            260
Sobreviveu                                1
Classe                                    2
Nome            Parrish, Mrs. (Lutie Davis)
Sexo                                 mulher
Idade                                  50.0
IrmaoConjuge                              0
PaisFilhos                                1
Bilhete                              230433
Tarifa                                 26.0
Cabine                                  NaN
Embarque                                  S
Classe Nova                          Classe
Name: 259, dtype: object
Linha: 260
Colunas:
IdPassageiro                  261
Sobreviveu                      0
Classe                          3
Nome            Smith, Mr. Thomas
Sexo                        homem
Idade                         NaN
IrmaoConjuge                    0
PaisFilhos                      0
Bilhete                    384461
Tarifa                       7.75
Cabine                        NaN
Embarque                        Q
Classe Nova           Classe alta
Name: 260, dtype: object
Linha: 261
Colunas:
IdPassageiro                                  262
Sobreviveu                                      1
Classe                                          3
Nome            Asplund, Master. Edvin Rojj Felix
Sexo                                        homem
Idade                                         3.0
IrmaoConjuge                                    4
PaisFilhos                                      2
Bilhete                                    347077
Tarifa                                    31.3875
Cabine                                        NaN
Embarque                                        S
Classe Nova                           Classe alta
Name: 261, dtype: object
Linha: 262
Colunas:
IdPassageiro                  263
Sobreviveu                      0
Classe                          1
Nome            Taussig, Mr. Emil
Sexo                        homem
Idade                        52.0
IrmaoConjuge                    1
PaisFilhos                      1
Bilhete                    110413
Tarifa                      79.65
Cabine                        E67
Embarque                        S
Classe Nova                Classe
Name: 262, dtype: object
Linha: 263
Colunas:
IdPassageiro                      264
Sobreviveu                          0
Classe                              1
Nome            Harrison, Mr. William
Sexo                            homem
Idade                            40.0
IrmaoConjuge                        0
PaisFilhos                          0
Bilhete                        112059
Tarifa                            0.0
Cabine                            B94
Embarque                            S
Classe Nova                    Classe
Name: 263, dtype: object
Linha: 264
Colunas:
IdPassageiro                   265
Sobreviveu                       0
Classe                           3
Nome            Henry, Miss. Delia
Sexo                        mulher
Idade                          NaN
IrmaoConjuge                     0
PaisFilhos                       0
Bilhete                     382649
Tarifa                        7.75
Cabine                         NaN
Embarque                         Q
Classe Nova            Classe alta
Name: 264, dtype: object
Linha: 265
Colunas:
IdPassageiro                  266
Sobreviveu                      0
Classe                          2
Nome            Reeves, Mr. David
Sexo                        homem
Idade                        36.0
IrmaoConjuge                    0
PaisFilhos                      0
Bilhete                C.A. 17248
Tarifa                       10.5
Cabine                        NaN
Embarque                        S
Classe Nova                Classe
Name: 265, dtype: object
Linha: 266
Colunas:
IdPassageiro                          267
Sobreviveu                              0
Classe                                  3
Nome            Panula, Mr. Ernesti Arvid
Sexo                                homem
Idade                                16.0
IrmaoConjuge                            4

Linha: 479
Colunas:
IdPassageiro                         480
Sobreviveu                             1
Classe                                 3
Nome            Hirvonen, Miss. Hildur E
Sexo                              mulher
Idade                                2.0
IrmaoConjuge                           0
PaisFilhos                             1
Bilhete                          3101298
Tarifa                           12.2875
Cabine                               NaN
Embarque                               S
Classe Nova                  Classe alta
Name: 479, dtype: object
Linha: 480
Colunas:
IdPassageiro                               481
Sobreviveu                                   0
Classe                                       3
Nome            Goodwin, Master. Harold Victor
Sexo                                     homem
Idade                                      9.0
IrmaoConjuge                                 5
PaisFilhos                                   2
Bilhete                                CA 2144
Tarifa                                    46.9
Cabine                                     NaN
Embarque                                     S
Classe Nova                        Classe alta
Name: 480, dtype: object
Linha: 481
Colunas:
IdPassageiro                                 482
Sobreviveu                                     0
Classe                                         2
Nome            Frost, Mr. Anthony Wood "Archie"
Sexo                                       homem
Idade                                        NaN
IrmaoConjuge                                   0
PaisFilhos                                     0
Bilhete                                   239854
Tarifa                                       0.0
Cabine                                       NaN
Embarque                                       S
Classe Nova                               Classe
Name: 481, dtype: object
Linha: 482
Colunas:
IdPassageiro                         483
Sobreviveu                             0
Classe                                 3
Nome            Rouse, Mr. Richard Henry
Sexo                               homem
Idade                               50.0
IrmaoConjuge                           0
PaisFilhos                             0
Bilhete                         A/5 3594
Tarifa                              8.05
Cabine                               NaN
Embarque                               S
Classe Nova                  Classe alta
Name: 482, dtype: object
Linha: 483
Colunas:
IdPassageiro                       484
Sobreviveu                           1
Classe                               3
Nome            Turkula, Mrs. (Hedwig)
Sexo                            mulher
Idade                             63.0
IrmaoConjuge                         0
PaisFilhos                           0
Bilhete                           4134
Tarifa                          9.5875
Cabine                             NaN
Embarque                             S
Classe Nova                Classe alta
Name: 483, dtype: object
Linha: 484
Colunas:
IdPassageiro                        485
Sobreviveu                            1
Classe                                1
Nome            Bishop, Mr. Dickinson H
Sexo                              homem
Idade                              25.0
IrmaoConjuge                          1
PaisFilhos                            0
Bilhete                           11967
Tarifa                          91.0792
Cabine                              B49
Embarque                              C
Classe Nova                      Classe
Name: 484, dtype: object
Linha: 485
Colunas:
IdPassageiro                       486
Sobreviveu                           0
Classe                               3
Nome            Lefebre, Miss. Jeannie
Sexo                            mulher
Idade                              NaN
IrmaoConjuge                         3
PaisFilhos                           1
Bilhete                           4133
Tarifa                         25.4667
Cabine                             NaN
Embarque                             S
Classe Nova                Classe alta
Name: 485, dtype: object
Linha: 486
Colunas:
IdPassageiro                                                487
Sobreviveu                                                    1
Classe                                                        1
Nome            Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)
Sexo                                                     mulher
Idade                                                      35.0
IrmaoConjuge                                                  1
PaisFilhos                                                    0
Bilhete                                                   19943
Tarifa                                                     90.0
Cabine                                                      C93
Embarque                                                      S
Classe Nova                                              Classe
Name: 486, dtype: object
Linha: 487
Colunas:
IdPassageiro                        488
Sobreviveu                            0
Classe                                1
Nome            Kent, Mr. Edward Austin
Sexo                              homem
Idade                              58.0
IrmaoConjuge                          0
PaisFilhos                            0
Bilhete                           11771
Tarifa                             29.7
Cabine                              B37
Embarque                              C
Classe Nova                      Classe
Name: 487, dtype: object
Linha: 488
Colunas:
IdPassageiro                              489
Sobreviveu                                  0
Classe                                      3
Nome            Somerton, Mr. Francis William
Sexo                                    homem
Idade                                    30.0
IrmaoConjuge                                0
PaisFilhos                                  0
Bilhete                            A.5. 18509
Tarifa                                   8.05
Cabine                                    NaN
Embarque                                    S
Classe Nova                       Classe alta
Name: 488, dtype: object
Linha: 489
Colunas:
IdPassageiro                                      490
Sobreviveu                                          1
Classe                                              3
Nome            Coutts, Master. Eden Leslie "Neville"
Sexo                                            homem
Idade                                             9.0
IrmaoConjuge                                        1
PaisFilhos                                          1
Bilhete                                    C.A. 37671
Tarifa                                           15.9
Cabine                                            NaN
Embarque                                            S
Classe Nova                               Classe alta
Name: 489, dtype: object
Linha: 490
Colunas:
IdPassageiro                                     491
Sobreviveu                                         0
Classe                                             3
Nome            Hagland, Mr. Konrad Mathias Reiersen
Sexo                                           homem
Idade                                            NaN
IrmaoConjuge                                       1
PaisFilhos                                         0
Bilhete                                        65304
Tarifa                                       19.9667
Cabine                                           NaN
Embarque                                           S
Classe Nova                              Classe alta
Name: 490, dtype: object
Linha: 491
Colunas:
IdPassageiro                    492
Sobreviveu                        0
Classe                            3
Nome            Windelov, Mr. Einar
Sexo                          homem
Idade                          21.0
IrmaoConjuge                      0
PaisFilhos                        0
Bilhete            SOTON/OQ 3101317
Tarifa                         7.25
Cabine                          NaN
Embarque                          S
Classe Nova             Classe alta
Name: 491, dtype: object
Linha: 492
Colunas:
IdPassageiro                           493
Sobreviveu                               0
Classe                                   1
Nome            Molson, Mr. Harry Markland
Sexo                                 homem
Idade                                 55.0
IrmaoConjuge                             0
PaisFilhos                               0
Bilhete                             113787
Tarifa                                30.5
Cabine                                 C30
Embarque                                 S
Classe Nova                         Classe
Name: 492, dtype: object
Linha: 493
Colunas:
IdPassageiro                        494
Sobreviveu                            0
Classe                                1
Nome            Artagaveytia, Mr. Ramon
Sexo                              homem
Idade                              71.0
IrmaoConjuge                          0
PaisFilhos                            0
Bilhete                        PC 17609
Tarifa                          49.5042
Cabine                              NaN
Embarque                              C
Classe Nova                      Classe
Name: 493, dtype: object
Linha: 494
Colunas:
IdPassageiro                           495
Sobreviveu                               0
Classe                                   3
Nome            Stanley, Mr. Edward Roland
Sexo                                 homem
Idade                                 21.0
IrmaoConjuge                             0
PaisFilhos                               0
Bilhete                          A/4 45380
Tarifa                                8.05
Cabine                                 NaN
Embarque                                 S
Classe Nova                    Classe alta
Name: 494, dtype: object
Linha: 495
Colunas:
IdPassageiro                      496
Sobreviveu                          0
Classe                              3
Nome            Yousseff, Mr. Gerious
Sexo                            homem
Idade                             NaN
IrmaoConjuge                        0
PaisFilhos                          0
Bilhete                          2627
Tarifa                        14.4583
Cabine                            NaN
Embarque                            C
Classe Nova               Classe alta
Name: 495, dtype: object
Linha: 496
Colunas:
IdPassageiro                               497
Sobreviveu                                   1
Classe                                       1
Nome            Eustis, Miss. Elizabeth Mussey
Sexo                                    mulher
Idade                                     54.0
IrmaoConjuge                                 1
PaisFilhos                                   0
Bilhete                                  36947
Tarifa                                 78.2667
Cabine                                     D20
Embarque                                     C
Classe Nova                             Classe
Name: 496, dtype: object
Linha: 497
Colunas:
IdPassageiro                                498
Sobreviveu                                    0
Classe                                        3
Nome            Shellard, Mr. Frederick William
Sexo                                      homem
Idade                                       NaN
IrmaoConjuge                                  0
PaisFilhos                                    0
Bilhete                               C.A. 6212
Tarifa                                     15.1
Cabine                                      NaN
Embarque                                      S
Classe Nova                         Classe alta
Name: 497, dtype: object
Linha: 498
Colunas:
IdPassageiro                                                499
Sobreviveu                                                    0
Classe                                                        1
Nome            Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
Sexo                                                     mulher
Idade                                                      25.0
IrmaoConjuge                                                  1
PaisFilhos                                                    2
Bilhete                                                  113781
Tarifa                                                   151.55
Cabine                                                  C22 C26
Embarque                                                      S
Classe Nova                                              Classe
Name: 498, dtype: object
Linha: 499
Colunas:
IdPassageiro                   500
Sobreviveu                       0
Classe                           3
Nome            Svensson, Mr. Olof
Sexo                         homem
Idade                         24.0
IrmaoConjuge                     0
PaisFilhos                       0
Bilhete                     350035
Tarifa                      7.7958
Cabine                         NaN
Embarque                         S
Classe Nova            Classe alta
Name: 499, dtype: object
Linha: 500
Colunas:
IdPassageiro                 501
Sobreviveu                     0
Classe                         3
Nome            Calic, Mr. Petar
Sexo                       homem
Idade                       17.0
IrmaoConjuge                   0
PaisFilhos                     0
Bilhete                   315086
Tarifa                    8.6625
Cabine                       NaN
Embarque                       S
Classe Nova          Classe alta
Name: 500, dtype: object
Linha: 501
Colunas:
IdPassageiro                    502
Sobreviveu                        0
Classe                            3
Nome            Canavan, Miss. Mary
Sexo                         mulher
Idade                          21.0
IrmaoConjuge                      0
PaisFilhos                        0
Bilhete                      364846
Tarifa                         7.75
Cabine                          NaN
Embarque                          Q
Classe Nova             Classe alta
Name: 501, dtype: object
Linha: 502
Colunas:
IdPassageiro                               503
Sobreviveu                                   0
Classe                                       3
Nome            O'Sullivan, Miss. Bridget Mary
Sexo                                    mulher
Idade                                      NaN
IrmaoConjuge                                 0
PaisFilhos                                   0
Bilhete                                 330909
Tarifa                                  7.6292
Cabine                                     NaN
Embarque                                     Q
Classe Nova                        Classe alta
Name: 502, dtype: object
Linha: 503
Colunas:
IdPassageiro                               504
Sobreviveu                                   0
Classe                                       3
Nome            Laitinen, Miss. Kristina Sofia
Sexo                                    mulher
Idade                                     37.0
IrmaoConjuge                                 0
PaisFilhos                                   0
Bilhete                                   4135
Tarifa                                  9.5875
Cabine                                     NaN
Embarque                                     S
Classe Nova                        Classe alta
Name: 503, dtype: object
Linha: 504
Colunas:
IdPassageiro                      505
Sobreviveu                          1
Classe                              1
Nome            Maioni, Miss. Roberta
Sexo                           mulher
Idade                            16.0
IrmaoConjuge                        0
PaisFilhos                          0
Bilhete                        110152
Tarifa                           86.5
Cabine                            B79
Embarque                            S
Classe Nova                    Classe
Name: 504, dtype: object
Linha: 505
Colunas:
IdPassageiro                                           506
Sobreviveu                                               0
Classe                                                   1
Nome            Penasco y Castellana, Mr. Victor de Satode
Sexo                                                 homem
Idade                                                 18.0
IrmaoConjuge                                             1
PaisFilhos                                               0
Bilhete                                           PC 17758
Tarifa                                               108.9
Cabine                                                 C65
Embarque                                                 C
Classe Nova                                         Classe
Name: 505, dtype: object
Linha: 506
Colunas:
IdPassageiro                                              507
Sobreviveu                                                  1
Classe                                                      2
Nome            Quick, Mrs. Frederick Charles (Jane Richards)
Sexo                                                   mulher
Idade                                                    33.0
IrmaoConjuge                                                0
PaisFilhos                                                  2
Bilhete                                                 26360
Tarifa                                                   26.0
Cabine                                                    NaN
Embarque                                                    S
Classe Nova                                            Classe
Name: 506, dtype: object
Linha: 507
Colunas:
IdPassageiro                                              508
Sobreviveu                                                  1
Classe                                                      1
Nome            Bradley, Mr. George ("George Arthur Brayton")
Sexo                                                    homem
Idade                                                     NaN
IrmaoConjuge                                                0
PaisFilhos                                                  0
Bilhete                                                111427
Tarifa                                                  26.55
Cabine                                                    NaN
Embarque                                                    S
Classe Nova                                            Classe
Name: 507, dtype: object
Linha: 508
Colunas:
IdPassageiro                         509
Sobreviveu                             0
Classe                                 3
Nome            Olsen, Mr. Henry Margido
Sexo                               homem
Idade                               28.0
IrmaoConjuge                           0
PaisFilhos                             0
Bilhete                           C 4001
Tarifa                            22.525
Cabine                               NaN
Embarque                               S
Classe Nova                  Classe alta
Name: 508, dtype: object
Linha: 509
Colunas:
IdPassageiro               510
Sobreviveu                   1
Classe                       3
Nome            Lang, Mr. Fang
Sexo                     homem
Idade                     26.0
IrmaoConjuge                 0
PaisFilhos                   0
Bilhete                   1601
Tarifa                 56.4958
Cabine                     NaN
Embarque                     S
Classe Nova        Classe alta
Name: 509, dtype: object
Linha: 510
Colunas:
IdPassageiro                         511
Sobreviveu                             1
Classe                                 3
Nome            Daly, Mr. Eugene Patrick
Sexo                               homem
Idade                               29.0
IrmaoConjuge                           0
PaisFilhos                             0

Name: 594, dtype: object
Linha: 595
Colunas:
IdPassageiro                            596
Sobreviveu                                0
Classe                                    3
Nome            Van Impe, Mr. Jean Baptiste
Sexo                                  homem
Idade                                  36.0
IrmaoConjuge                              1
PaisFilhos                                1
Bilhete                              345773
Tarifa                                24.15
Cabine                                  NaN
Embarque                                  S
Classe Nova                     Classe alta
Name: 595, dtype: object
Linha: 596
Colunas:
IdPassageiro                           597
Sobreviveu                               1
Classe                                   2
Nome            Leitch, Miss. Jessie Wills
Sexo                                mulher
Idade                                  NaN
IrmaoConjuge                             0
PaisFilhos                               0
Bilhete                             248727
Tarifa                                33.0
Cabine                                 NaN
Embarque                                 S
Classe Nova                         Classe
Name: 596, dtype: object
Linha: 597
Colunas:
IdPassageiro                    598
Sobreviveu                        0
Classe                            3
Nome            Johnson, Mr. Alfred
Sexo                          homem
Idade                          49.0
IrmaoConjuge                      0
PaisFilhos                        0
Bilhete                        LINE
Tarifa                          0.0
Cabine                          NaN
Embarque                          S
Classe Nova             Classe alta
Name: 597, dtype: object
Linha: 598
Colunas:
IdPassageiro                  599
Sobreviveu                      0
Classe                          3
Nome            Boulos, Mr. Hanna
Sexo                        homem
Idade                         NaN
IrmaoConjuge                    0
PaisFilhos                      0
Bilhete                      2664
Tarifa                      7.225
Cabine                        NaN
Embarque                        C
Classe Nova           Classe alta
Name: 598, dtype: object
Linha: 599
Colunas:
IdPassageiro                                             600
Sobreviveu                                                 1
Classe                                                     1
Nome            Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")
Sexo                                                   homem
Idade                                                   49.0
IrmaoConjuge                                               1
PaisFilhos                                                 0
Bilhete                                             PC 17485
Tarifa                                               56.9292
Cabine                                                   A20
Embarque                                                   C
Classe Nova                                           Classe
Name: 599, dtype: object
Linha: 600
Colunas:
IdPassageiro                                                  601
Sobreviveu                                                      1
Classe                                                          2
Nome            Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...
Sexo                                                       mulher
Idade                                                        24.0
IrmaoConjuge                                                    2
PaisFilhos                                                      1
Bilhete                                                    243847
Tarifa                                                       27.0
Cabine                                                        NaN
Embarque                                                        S
Classe Nova                                                Classe
Name: 600, dtype: object
Linha: 601
Colunas:
IdPassageiro                     602
Sobreviveu                         0
Classe                             3
Nome            Slabenoff, Mr. Petco
Sexo                           homem
Idade                            NaN
IrmaoConjuge                       0
PaisFilhos                         0
Bilhete                       349214
Tarifa                        7.8958
Cabine                           NaN
Embarque                           S
Classe Nova              Classe alta
Name: 601, dtype: object
Linha: 602
Colunas:
IdPassageiro                          603
Sobreviveu                              0
Classe                                  1
Nome            Harrington, Mr. Charles H
Sexo                                homem
Idade                                 NaN
IrmaoConjuge                            0
PaisFilhos                              0
Bilhete                            113796
Tarifa                               42.4
Cabine                                NaN
Embarque                                S
Classe Nova                        Classe
Name: 602, dtype: object
Linha: 603
Colunas:
IdPassageiro                          604
Sobreviveu                              0
Classe                                  3
Nome            Torber, Mr. Ernst William
Sexo                                homem
Idade                                44.0
IrmaoConjuge                            0
PaisFilhos                              0
Bilhete                            364511
Tarifa                               8.05
Cabine                                NaN
Embarque                                S
Classe Nova                   Classe alta
Name: 603, dtype: object
Linha: 604
Colunas:
IdPassageiro                                605
Sobreviveu                                    1
Classe                                        1
Nome            Homer, Mr. Harry ("Mr E Haven")
Sexo                                      homem
Idade                                      35.0
IrmaoConjuge                                  0
PaisFilhos                                    0
Bilhete                                  111426
Tarifa                                    26.55
Cabine                                      NaN
Embarque                                      C
Classe Nova                              Classe
Name: 604, dtype: object
Linha: 605
Colunas:
IdPassageiro                              606
Sobreviveu                                  0
Classe                                      3
Nome            Lindell, Mr. Edvard Bengtsson
Sexo                                    homem
Idade                                    36.0
IrmaoConjuge                                1
PaisFilhos                                  0
Bilhete                                349910
Tarifa                                  15.55
Cabine                                    NaN
Embarque                                    S
Classe Nova                       Classe alta
Name: 605, dtype: object
Linha: 606
Colunas:
IdPassageiro                  607
Sobreviveu                      0
Classe                          3
Nome            Karaic, Mr. Milan
Sexo                        homem
Idade                        30.0
IrmaoConjuge                    0
PaisFilhos                      0
Bilhete                    349246
Tarifa                     7.8958
Cabine                        NaN
Embarque                        S
Classe Nova           Classe alta
Name: 606, dtype: object
Linha: 607
Colunas:
IdPassageiro                            608
Sobreviveu                                1
Classe                                    1
Nome            Daniel, Mr. Robert Williams
Sexo                                  homem
Idade                                  27.0
IrmaoConjuge                              0
PaisFilhos                                0
Bilhete                              113804
Tarifa                                 30.5
Cabine                                  NaN
Embarque                                  S
Classe Nova                          Classe
Name: 607, dtype: object
Linha: 608
Colunas:
IdPassageiro                                                  609
Sobreviveu                                                      1
Classe                                                          2
Nome            Laroche, Mrs. Joseph (Juliette Marie Louise La...
Sexo                                                       mulher
Idade                                                        22.0
IrmaoConjuge                                                    1
PaisFilhos                                                      2
Bilhete                                             SC/Paris 2123
Tarifa                                                    41.5792
Cabine                                                        NaN
Embarque                                                        C
Classe Nova                                                Classe
Name: 608, dtype: object
Linha: 609
Colunas:
IdPassageiro                          610
Sobreviveu                              1
Classe                                  1
Nome            Shutes, Miss. Elizabeth W
Sexo                               mulher
Idade                                40.0
IrmaoConjuge                            0
PaisFilhos                              0
Bilhete                          PC 17582
Tarifa                           153.4625
Cabine                               C125
Embarque                                S
Classe Nova                        Classe
Name: 609, dtype: object
Linha: 610
Colunas:
IdPassageiro                                                  611
Sobreviveu                                                      0
Classe                                                          3
Nome            Andersson, Mrs. Anders Johan (Alfrida Konstant...
Sexo                                                       mulher
Idade                                                        39.0
IrmaoConjuge                                                    1
PaisFilhos                                                      5
Bilhete                                                    347082
Tarifa                                                     31.275
Cabine                                                        NaN
Embarque                                                        S
Classe Nova                                           Classe alta
Name: 610, dtype: object
Linha: 611
Colunas:
IdPassageiro                      612
Sobreviveu                          0
Classe                              3
Nome            Jardin, Mr. Jose Neto
Sexo                            homem
Idade                             NaN
IrmaoConjuge                        0
PaisFilhos                          0
Bilhete            SOTON/O.Q. 3101305
Tarifa                           7.05
Cabine                            NaN
Embarque                            S
Classe Nova               Classe alta
Name: 611, dtype: object
Linha: 612
Colunas:
IdPassageiro                            613
Sobreviveu                                1
Classe                                    3
Nome            Murphy, Miss. Margaret Jane
Sexo                                 mulher
Idade                                   NaN
IrmaoConjuge                              1
PaisFilhos                                0
Bilhete                              367230
Tarifa                                 15.5
Cabine                                  NaN
Embarque                                  Q
Classe Nova                     Classe alta
Name: 612, dtype: object
Linha: 613
Colunas:
IdPassageiro                 614
Sobreviveu                     0
Classe                         3
Nome            Horgan, Mr. John
Sexo                       homem
Idade                        NaN
IrmaoConjuge                   0
PaisFilhos                     0
Bilhete                   370377
Tarifa                      7.75
Cabine                       NaN
Embarque                       Q
Classe Nova          Classe alta
Name: 613, dtype: object
Linha: 614
Colunas:
IdPassageiro                                615
Sobreviveu                                    0
Classe                                        3
Nome            Brocklebank, Mr. William Alfred
Sexo                                      homem
Idade                                      35.0
IrmaoConjuge                                  0
PaisFilhos                                    0
Bilhete                                  364512
Tarifa                                     8.05
Cabine                                      NaN
Embarque                                      S
Classe Nova                         Classe alta
Name: 614, dtype: object
Linha: 615
Colunas:
IdPassageiro                    616
Sobreviveu                        1
Classe                            2
Nome            Herman, Miss. Alice
Sexo                         mulher
Idade                          24.0
IrmaoConjuge                      1
PaisFilhos                        2
Bilhete                      220845
Tarifa                         65.0
Cabine                          NaN
Embarque                          S
Classe Nova                  Classe
Name: 615, dtype: object
Linha: 616
Colunas:
IdPassageiro                          617
Sobreviveu                              0
Classe                                  3
Nome            Danbom, Mr. Ernst Gilbert
Sexo                                homem
Idade                                34.0
IrmaoConjuge                            1
PaisFilhos                              1
Bilhete                            347080
Tarifa                               14.4
Cabine                                NaN
Embarque                                S
Classe Nova                   Classe alta
Name: 616, dtype: object
Linha: 617
Colunas:
IdPassageiro                                                618
Sobreviveu                                                    0
Classe                                                        3
Nome            Lobb, Mrs. William Arthur (Cordelia K Stanlick)
Sexo                                                     mulher
Idade                                                      26.0
IrmaoConjuge                                                  1
PaisFilhos                                                    0
Bilhete                                               A/5. 3336
Tarifa                                                     16.1
Cabine                                                      NaN
Embarque                                                      S
Classe Nova                                         Classe alta
Name: 617, dtype: object
Linha: 618
Colunas:
IdPassageiro                            619
Sobreviveu                                1
Classe                                    2
Nome            Becker, Miss. Marion Louise
Sexo                                 mulher
Idade                                   4.0
IrmaoConjuge                              2
PaisFilhos                                1
Bilhete                              230136
Tarifa                                 39.0
Cabine                                   F4
Embarque                                  S
Classe Nova                          Classe
Name: 618, dtype: object
Linha: 619
Colunas:
IdPassageiro                    620
Sobreviveu                        0
Classe                            2
Nome            Gavey, Mr. Lawrence
Sexo                          homem
Idade                          26.0
IrmaoConjuge                      0
PaisFilhos                        0
Bilhete                       31028
Tarifa                         10.5
Cabine                          NaN
Embarque                          S
Classe Nova                  Classe
Name: 619, dtype: object
Linha: 620
Colunas:
IdPassageiro                    621
Sobreviveu                        0
Classe                            3
Nome            Yasbeck, Mr. Antoni
Sexo                          homem
Idade                          27.0
IrmaoConjuge                      1
PaisFilhos                        0
Bilhete                        2659
Tarifa                      14.4542
Cabine                          NaN
Embarque                          C
Classe Nova             Classe alta
Name: 620, dtype: object
Linha: 621
Colunas:
IdPassageiro                             622
Sobreviveu                                 1
Classe                                     1
Nome            Kimball, Mr. Edwin Nelson Jr
Sexo                                   homem
Idade                                   42.0
IrmaoConjuge                               1
PaisFilhos                                 0
Bilhete                                11753
Tarifa                               52.5542
Cabine                                   D19
Embarque                                   S
Classe Nova                           Classe
Name: 621, dtype: object
Linha: 622
Colunas:
IdPassageiro                 623
Sobreviveu                     1
Classe                         3
Nome            Nakid, Mr. Sahid
Sexo                       homem
Idade                       20.0
IrmaoConjuge                   1
PaisFilhos                     1
Bilhete                     2653
Tarifa                   15.7417
Cabine                       NaN
Embarque                       C
Classe Nova          Classe alta
Name: 622, dtype: object
Linha: 623
Colunas:
IdPassageiro                            624
Sobreviveu                                0
Classe                                    3
Nome            Hansen, Mr. Henry Damsgaard
Sexo                                  homem
Idade                                  21.0
IrmaoConjuge                              0
PaisFilhos                                0
Bilhete                              350029
Tarifa                               7.8542
Cabine                                  NaN
Embarque                                  S
Classe Nova                     Classe alta
Name: 623, dtype: object
Linha: 624
Colunas:
IdPassageiro                            625
Sobreviveu                                0
Classe                                    3
Nome            Bowen, Mr. David John "Dai"
Sexo                                  homem
Idade                                  21.0
IrmaoConjuge                              0
PaisFilhos                                0
Bilhete                               54636
Tarifa                                 16.1
Cabine                                  NaN
Embarque                                  S
Classe Nova                     Classe alta
Name: 624, dtype: object
Linha: 625
Colunas:
IdPassageiro                      626
Sobreviveu                          0
Classe                              1
Nome            Sutton, Mr. Frederick
Sexo                            homem
Idade                            61.0
IrmaoConjuge                        0
PaisFilhos                          0
Bilhete                         36963
Tarifa                        32.3208
Cabine                            D50
Embarque                            S
Classe Nova                    Classe
Name: 625, dtype: object
Linha: 626
Colunas:
IdPassageiro                               627
Sobreviveu                                   0
Classe                                       2
Nome            Kirkland, Rev. Charles Leonard
Sexo                                     homem
Idade                                     57.0
IrmaoConjuge                                 0
PaisFilhos                                   0
Bilhete                                 219533
Tarifa                                   12.35
Cabine                                     NaN
Embarque                                     Q
Classe Nova                             Classe
Name: 626, dtype: object
Linha: 627
Colunas:

Name: 761, dtype: object
Linha: 762
Colunas:
IdPassageiro                      763
Sobreviveu                          1
Classe                              3
Nome            Barah, Mr. Hanna Assi
Sexo                            homem
Idade                            20.0
IrmaoConjuge                        0
PaisFilhos                          0
Bilhete                          2663
Tarifa                         7.2292
Cabine                            NaN
Embarque                            C
Classe Nova               Classe alta
Name: 762, dtype: object
Linha: 763
Colunas:
IdPassageiro                                          764
Sobreviveu                                              1
Classe                                                  1
Nome            Carter, Mrs. William Ernest (Lucile Polk)
Sexo                                               mulher
Idade                                                36.0
IrmaoConjuge                                            1
PaisFilhos                                              2
Bilhete                                            113760
Tarifa                                              120.0
Cabine                                            B96 B98
Embarque                                                S
Classe Nova                                        Classe
Name: 763, dtype: object
Linha: 764
Colunas:
IdPassageiro                       765
Sobreviveu                           0
Classe                               3
Nome            Eklund, Mr. Hans Linus
Sexo                             homem
Idade                             16.0
IrmaoConjuge                         0
PaisFilhos                           0
Bilhete                         347074
Tarifa                           7.775
Cabine                             NaN
Embarque                             S
Classe Nova                Classe alta
Name: 764, dtype: object
Linha: 765
Colunas:
IdPassageiro                                     766
Sobreviveu                                         1
Classe                                             1
Nome            Hogeboom, Mrs. John C (Anna Andrews)
Sexo                                          mulher
Idade                                           51.0
IrmaoConjuge                                       1
PaisFilhos                                         0
Bilhete                                        13502
Tarifa                                       77.9583
Cabine                                           D11
Embarque                                           S
Classe Nova                                   Classe
Name: 765, dtype: object
Linha: 766
Colunas:
IdPassageiro                          767
Sobreviveu                              0
Classe                                  1
Nome            Brewe, Dr. Arthur Jackson
Sexo                                homem
Idade                                 NaN
IrmaoConjuge                            0
PaisFilhos                              0
Bilhete                            112379
Tarifa                               39.6
Cabine                                NaN
Embarque                                C
Classe Nova                        Classe
Name: 766, dtype: object
Linha: 767
Colunas:
IdPassageiro                   768
Sobreviveu                       0
Classe                           3
Nome            Mangan, Miss. Mary
Sexo                        mulher
Idade                         30.5
IrmaoConjuge                     0
PaisFilhos                       0
Bilhete                     364850
Tarifa                        7.75
Cabine                         NaN
Embarque                         Q
Classe Nova            Classe alta
Name: 767, dtype: object
Linha: 768
Colunas:
IdPassageiro                    769
Sobreviveu                        0
Classe                            3
Nome            Moran, Mr. Daniel J
Sexo                          homem
Idade                           NaN
IrmaoConjuge                      1
PaisFilhos                        0
Bilhete                      371110
Tarifa                        24.15
Cabine                          NaN
Embarque                          Q
Classe Nova             Classe alta
Name: 768, dtype: object
Linha: 769
Colunas:
IdPassageiro                                 770
Sobreviveu                                     0
Classe                                         3
Nome            Gronnestad, Mr. Daniel Danielsen
Sexo                                       homem
Idade                                       32.0
IrmaoConjuge                                   0
PaisFilhos                                     0
Bilhete                                     8471
Tarifa                                    8.3625
Cabine                                       NaN
Embarque                                       S
Classe Nova                          Classe alta
Name: 769, dtype: object
Linha: 770
Colunas:
IdPassageiro                       771
Sobreviveu                           0
Classe                               3
Nome            Lievens, Mr. Rene Aime
Sexo                             homem
Idade                             24.0
IrmaoConjuge                         0
PaisFilhos                           0
Bilhete                         345781
Tarifa                             9.5
Cabine                             NaN
Embarque                             S
Classe Nova                Classe alta
Name: 770, dtype: object
Linha: 771
Colunas:
IdPassageiro                        772
Sobreviveu                            0
Classe                                3
Nome            Jensen, Mr. Niels Peder
Sexo                              homem
Idade                              48.0
IrmaoConjuge                          0
PaisFilhos                            0
Bilhete                          350047
Tarifa                           7.8542
Cabine                              NaN
Embarque                              S
Classe Nova                 Classe alta
Name: 771, dtype: object
Linha: 772
Colunas:
IdPassageiro                  773
Sobreviveu                      0
Classe                          2
Nome            Mack, Mrs. (Mary)
Sexo                       mulher
Idade                        57.0
IrmaoConjuge                    0
PaisFilhos                      0
Bilhete               S.O./P.P. 3
Tarifa                       10.5
Cabine                        E77
Embarque                        S
Classe Nova                Classe
Name: 772, dtype: object
Linha: 773
Colunas:
IdPassageiro                774
Sobreviveu                    0
Classe                        3
Nome            Elias, Mr. Dibo
Sexo                      homem
Idade                       NaN
IrmaoConjuge                  0
PaisFilhos                    0
Bilhete                    2674
Tarifa                    7.225
Cabine                      NaN
Embarque                      C
Classe Nova         Classe alta
Name: 773, dtype: object
Linha: 774
Colunas:
IdPassageiro                                      775
Sobreviveu                                          1
Classe                                              2
Nome            Hocking, Mrs. Elizabeth (Eliza Needs)
Sexo                                           mulher
Idade                                            54.0
IrmaoConjuge                                        1
PaisFilhos                                          3
Bilhete                                         29105
Tarifa                                           23.0
Cabine                                            NaN
Embarque                                            S
Classe Nova                                    Classe
Name: 774, dtype: object
Linha: 775
Colunas:
IdPassageiro                                        776
Sobreviveu                                            0
Classe                                                3
Nome            Myhrman, Mr. Pehr Fabian Oliver Malkolm
Sexo                                              homem
Idade                                              18.0
IrmaoConjuge                                          0
PaisFilhos                                            0
Bilhete                                          347078
Tarifa                                             7.75
Cabine                                              NaN
Embarque                                              S
Classe Nova                                 Classe alta
Name: 775, dtype: object
Linha: 776
Colunas:
IdPassageiro                 777
Sobreviveu                     0
Classe                         3
Nome            Tobin, Mr. Roger
Sexo                       homem
Idade                        NaN
IrmaoConjuge                   0
PaisFilhos                     0
Bilhete                   383121
Tarifa                      7.75
Cabine                       F38
Embarque                       Q
Classe Nova          Classe alta
Name: 776, dtype: object
Linha: 777
Colunas:
IdPassageiro                              778
Sobreviveu                                  1
Classe                                      3
Nome            Emanuel, Miss. Virginia Ethel
Sexo                                   mulher
Idade                                     5.0
IrmaoConjuge                                0
PaisFilhos                                  0
Bilhete                                364516
Tarifa                                 12.475
Cabine                                    NaN
Embarque                                    S
Classe Nova                       Classe alta
Name: 777, dtype: object
Linha: 778
Colunas:
IdPassageiro                        779
Sobreviveu                            0
Classe                                3
Nome            Kilgannon, Mr. Thomas J
Sexo                              homem
Idade                               NaN
IrmaoConjuge                          0
PaisFilhos                            0
Bilhete                           36865
Tarifa                           7.7375
Cabine                              NaN
Embarque                              Q
Classe Nova                 Classe alta
Name: 778, dtype: object
Linha: 779
Colunas:
IdPassageiro                                                  780
Sobreviveu                                                      1
Classe                                                          1
Nome            Robert, Mrs. Edward Scott (Elisabeth Walton Mc...
Sexo                                                       mulher
Idade                                                        43.0
IrmaoConjuge                                                    0
PaisFilhos                                                      1
Bilhete                                                     24160
Tarifa                                                   211.3375
Cabine                                                         B3
Embarque                                                        S
Classe Nova                                                Classe
Name: 779, dtype: object
Linha: 780
Colunas:
IdPassageiro                     781
Sobreviveu                         1
Classe                             3
Nome            Ayoub, Miss. Banoura
Sexo                          mulher
Idade                           13.0
IrmaoConjuge                       0
PaisFilhos                         0
Bilhete                         2687
Tarifa                        7.2292
Cabine                           NaN
Embarque                           C
Classe Nova              Classe alta
Name: 780, dtype: object
Linha: 781
Colunas:
IdPassageiro                                          782
Sobreviveu                                              1
Classe                                                  1
Nome            Dick, Mrs. Albert Adrian (Vera Gillespie)
Sexo                                               mulher
Idade                                                17.0
IrmaoConjuge                                            1
PaisFilhos                                              0
Bilhete                                             17474
Tarifa                                               57.0
Cabine                                                B20
Embarque                                                S
Classe Nova                                        Classe
Name: 781, dtype: object
Linha: 782
Colunas:
IdPassageiro                       783
Sobreviveu                           0
Classe                               1
Nome            Long, Mr. Milton Clyde
Sexo                             homem
Idade                             29.0
IrmaoConjuge                         0
PaisFilhos                           0
Bilhete                         113501
Tarifa                            30.0
Cabine                              D6
Embarque                             S
Classe Nova                     Classe
Name: 782, dtype: object
Linha: 783
Colunas:
IdPassageiro                       784
Sobreviveu                           0
Classe                               3
Nome            Johnston, Mr. Andrew G
Sexo                             homem
Idade                              NaN
IrmaoConjuge                         1
PaisFilhos                           2
Bilhete                     W./C. 6607
Tarifa                           23.45
Cabine                             NaN
Embarque                             S
Classe Nova                Classe alta
Name: 783, dtype: object
Linha: 784
Colunas:
IdPassageiro                   785
Sobreviveu                       0
Classe                           3
Nome              Ali, Mr. William
Sexo                         homem
Idade                         25.0
IrmaoConjuge                     0
PaisFilhos                       0
Bilhete         SOTON/O.Q. 3101312
Tarifa                        7.05
Cabine                         NaN
Embarque                         S
Classe Nova            Classe alta
Name: 784, dtype: object
Linha: 785
Colunas:
IdPassageiro                                   786
Sobreviveu                                       0
Classe                                           3
Nome            Harmer, Mr. Abraham (David Lishin)
Sexo                                         homem
Idade                                         25.0
IrmaoConjuge                                     0
PaisFilhos                                       0
Bilhete                                     374887
Tarifa                                        7.25
Cabine                                         NaN
Embarque                                         S
Classe Nova                            Classe alta
Name: 785, dtype: object
Linha: 786
Colunas:
IdPassageiro                          787
Sobreviveu                              1
Classe                                  3
Nome            Sjoblom, Miss. Anna Sofia
Sexo                               mulher
Idade                                18.0
IrmaoConjuge                            0
PaisFilhos                              0
Bilhete                           3101265
Tarifa                             7.4958
Cabine                                NaN
Embarque                                S
Classe Nova                   Classe alta
Name: 786, dtype: object
Linha: 787
Colunas:
IdPassageiro                          788
Sobreviveu                              0
Classe                                  3
Nome            Rice, Master. George Hugh
Sexo                                homem
Idade                                 8.0
IrmaoConjuge                            4
PaisFilhos                              1
Bilhete                            382652
Tarifa                             29.125
Cabine                                NaN
Embarque                                Q
Classe Nova                   Classe alta
Name: 787, dtype: object
Linha: 788
Colunas:
IdPassageiro                           789
Sobreviveu                               1
Classe                                   3
Nome            Dean, Master. Bertram Vere
Sexo                                 homem
Idade                                  1.0
IrmaoConjuge                             1
PaisFilhos                               2
Bilhete                          C.A. 2315
Tarifa                              20.575
Cabine                                 NaN
Embarque                                 S
Classe Nova                    Classe alta
Name: 788, dtype: object
Linha: 789
Colunas:
IdPassageiro                         790
Sobreviveu                             0
Classe                                 1
Nome            Guggenheim, Mr. Benjamin
Sexo                               homem
Idade                               46.0
IrmaoConjuge                           0
PaisFilhos                             0
Bilhete                         PC 17593
Tarifa                              79.2
Cabine                           B82 B84
Embarque                               C
Classe Nova                       Classe
Name: 789, dtype: object
Linha: 790
Colunas:
IdPassageiro                         791
Sobreviveu                             0
Classe                                 3
Nome            Keane, Mr. Andrew "Andy"
Sexo                               homem
Idade                                NaN
IrmaoConjuge                           0
PaisFilhos                             0
Bilhete                            12460
Tarifa                              7.75
Cabine                               NaN
Embarque                               Q
Classe Nova                  Classe alta
Name: 790, dtype: object
Linha: 791
Colunas:
IdPassageiro                    792
Sobreviveu                        0
Classe                            2
Nome            Gaskell, Mr. Alfred
Sexo                          homem
Idade                          16.0
IrmaoConjuge                      0
PaisFilhos                        0
Bilhete                      239865
Tarifa                         26.0
Cabine                          NaN
Embarque                          S
Classe Nova                  Classe
Name: 791, dtype: object
Linha: 792
Colunas:
IdPassageiro                        793
Sobreviveu                            0
Classe                                3
Nome            Sage, Miss. Stella Anna
Sexo                             mulher
Idade                               NaN
IrmaoConjuge                          8
PaisFilhos                            2
Bilhete                        CA. 2343
Tarifa                            69.55
Cabine                              NaN
Embarque                              S
Classe Nova                 Classe alta
Name: 792, dtype: object
Linha: 793
Colunas:
IdPassageiro                         794
Sobreviveu                             0
Classe                                 1
Nome            Hoyt, Mr. William Fisher
Sexo                               homem
Idade                                NaN
IrmaoConjuge                           0
PaisFilhos                             0
Bilhete                         PC 17600
Tarifa                           30.6958
Cabine                               NaN
Embarque                               C
Classe Nova                       Classe
Name: 793, dtype: object
Linha: 794
Colunas:
IdPassageiro                      795
Sobreviveu                          0
Classe                              3
Nome            Dantcheff, Mr. Ristiu
Sexo                            homem
Idade                            25.0
IrmaoConjuge                        0
PaisFilhos                          0
Bilhete                        349203
Tarifa                         7.8958
Cabine                            NaN
Embarque                            S
Classe Nova               Classe alta
Name: 794, dtype: object
Linha: 795
Colunas:
IdPassageiro                   796
Sobreviveu                       0

Name: 879, dtype: object
Linha: 880
Colunas:
IdPassageiro                                             881
Sobreviveu                                                 1
Classe                                                     2
Nome            Shelley, Mrs. William (Imanita Parrish Hall)
Sexo                                                  mulher
Idade                                                   25.0
IrmaoConjuge                                               0
PaisFilhos                                                 1
Bilhete                                               230433
Tarifa                                                  26.0
Cabine                                                   NaN
Embarque                                                   S
Classe Nova                                           Classe
Name: 880, dtype: object
Linha: 881
Colunas:
IdPassageiro                   882
Sobreviveu                       0
Classe                           3
Nome            Markun, Mr. Johann
Sexo                         homem
Idade                         33.0
IrmaoConjuge                     0
PaisFilhos                       0
Bilhete                     349257
Tarifa                      7.8958
Cabine                         NaN
Embarque                         S
Classe Nova            Classe alta
Name: 881, dtype: object
Linha: 882
Colunas:
IdPassageiro                             883
Sobreviveu                                 0
Classe                                     3
Nome            Dahlberg, Miss. Gerda Ulrika
Sexo                                  mulher
Idade                                   22.0
IrmaoConjuge                               0
PaisFilhos                                 0
Bilhete                                 7552
Tarifa                               10.5167
Cabine                                   NaN
Embarque                                   S
Classe Nova                      Classe alta
Name: 882, dtype: object
Linha: 883
Colunas:
IdPassageiro                              884
Sobreviveu                                  0
Classe                                      2
Nome            Banfield, Mr. Frederick James
Sexo                                    homem
Idade                                    28.0
IrmaoConjuge                                0
PaisFilhos                                  0
Bilhete                      C.A./SOTON 34068
Tarifa                                   10.5
Cabine                                    NaN
Embarque                                    S
Classe Nova                            Classe
Name: 883, dtype: object
Linha: 884
Colunas:
IdPassageiro                       885
Sobreviveu                           0
Classe                               3
Nome            Sutehall, Mr. Henry Jr
Sexo                             homem
Idade                             25.0
IrmaoConjuge                         0
PaisFilhos                           0
Bilhete                SOTON/OQ 392076
Tarifa                            7.05
Cabine                             NaN
Embarque                             S
Classe Nova                Classe alta
Name: 884, dtype: object
Linha: 885
Colunas:
IdPassageiro                                     886
Sobreviveu                                         0
Classe                                             3
Nome            Rice, Mrs. William (Margaret Norton)
Sexo                                          mulher
Idade                                           39.0
IrmaoConjuge                                       0
PaisFilhos                                         5
Bilhete                                       382652
Tarifa                                        29.125
Cabine                                           NaN
Embarque                                           Q
Classe Nova                              Classe alta
Name: 885, dtype: object
Linha: 886
Colunas:
IdPassageiro                      887
Sobreviveu                          0
Classe                              2
Nome            Montvila, Rev. Juozas
Sexo                            homem
Idade                            27.0
IrmaoConjuge                        0
PaisFilhos                          0
Bilhete                        211536
Tarifa                           13.0
Cabine                            NaN
Embarque                            S
Classe Nova                    Classe
Name: 886, dtype: object
Linha: 887
Colunas:
IdPassageiro                             888
Sobreviveu                                 1
Classe                                     1
Nome            Graham, Miss. Margaret Edith
Sexo                                  mulher
Idade                                   19.0
IrmaoConjuge                               0
PaisFilhos                                 0
Bilhete                               112053
Tarifa                                  30.0
Cabine                                   B42
Embarque                                   S
Classe Nova                           Classe
Name: 887, dtype: object
Linha: 888
Colunas:
IdPassageiro                                         889
Sobreviveu                                             0
Classe                                                 3
Nome            Johnston, Miss. Catherine Helen "Carrie"
Sexo                                              mulher
Idade                                                NaN
IrmaoConjuge                                           1
PaisFilhos                                             2
Bilhete                                       W./C. 6607
Tarifa                                             23.45
Cabine                                               NaN
Embarque                                               S
Classe Nova                                  Classe alta
Name: 888, dtype: object
Linha: 889
Colunas:
IdPassageiro                      890
Sobreviveu                          1
Classe                              1
Nome            Behr, Mr. Karl Howell
Sexo                            homem
Idade                            26.0
IrmaoConjuge                        0
PaisFilhos                          0
Bilhete                        111369
Tarifa                           30.0
Cabine                           C148
Embarque                            C
Classe Nova                    Classe
Name: 889, dtype: object
Linha: 890
Colunas:
IdPassageiro                    891
Sobreviveu                        0
Classe                            3
Nome            Dooley, Mr. Patrick
Sexo                          homem
Idade                          32.0
IrmaoConjuge                      0
PaisFilhos                        0
Bilhete                      370376
Tarifa                         7.75
Cabine                          NaN
Embarque                          Q
Classe Nova             Classe alta
Name: 890, dtype: object

In [34]:
for coluna in data.columns:
    data[coluna]

In [32]:
for coluna, valor in data.iteritems():
    print(valor[2])
    break
coluna, valor

3

('IdPassageiro',
 0        1
 1        2
 2        3
 3        4
 4        5
       ...
 886    887
 887    888
 888    889
 889    890
 890    891
 Name: IdPassageiro, Length: 891, dtype: int64)

In [24]:
for nome, valores in data.iteritems():
    break
nome, valores

('IdPassageiro',
 0        1
 1        2
 2        3
 3        4
 4        5
       ...
 886    887
 887    888
 888    889
 889    890
 890    891
 Name: IdPassageiro, Length: 891, dtype: int64)

In [33]:
moda = {}
for nome, valores in data.iteritems():
    moda[nome] = valores.mode()[0]
moda

{'IdPassageiro': 1,
 'Sobreviveu': 0,
 'Classe': 3,
 'Nome': 'Abbing, Mr. Anthony',
 'Sexo': 'homem',
 'Idade': 24.0,
 'IrmaoConjuge': 0,
 'PaisFilhos': 0,
 'Bilhete': '1601',
 'Tarifa': 8.05,
 'Cabine': 'B96 B98',
 'Embarque': 'S',
 'Classe Nova': 'Classe alta'}

In [40]:
classe = []
for nome, valores in data.iteritems():
    print(f'nome: {nome}')
    print(f' valor: {valores[0]}')
    print('Classe alta' if valores[0] ==3 else 'Classe')

nome: IdPassageiro
 valor: 1
Classe
nome: Sobreviveu
 valor: 0
Classe
nome: Classe
 valor: 3
Classe alta
nome: Nome
 valor: Braund, Mr. Owen Harris
Classe
nome: Sexo
 valor: homem
Classe
nome: Idade
 valor: 22.0
Classe
nome: IrmaoConjuge
 valor: 1
Classe
nome: PaisFilhos
 valor: 0
Classe
nome: Bilhete
 valor: A/5 21171
Classe
nome: Tarifa
 valor: 7.25
Classe
nome: Cabine
 valor: nan
Classe
nome: Embarque
 valor: S
Classe
nome: Classe Nova
 valor: Classe alta
Classe